// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *TestOK) setDefaults() {
	{
		val := string("first")
		s.First.SetTo(Str(val))
	}
	{
		val := string("second")
		s.Second.SetTo(Str(val))
	}
}
