// Code generated by ogen, DO NOT EDIT.

package api

// NewOptStr returns new OptStr with value set to v.
func NewOptStr(v Str) OptStr {
	return OptStr{
		Value: v,
		Set:   true,
	}
}

// OptStr is optional Str.
type OptStr struct {
	Value Str
	Set   bool
}

// IsSet returns true if OptStr was set.
func (o OptStr) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptStr) Reset() {
	var v Str
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptStr) SetTo(v Str) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptStr) Get() (v Str, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptStr) Or(d Str) Str {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type Str string

type TestOK struct {
	First  OptStr `json:"first"`
	Second OptStr `json:"second"`
	Third  OptStr `json:"third"`
}

// GetFirst returns the value of First.
func (s *TestOK) GetFirst() OptStr {
	return s.First
}

// GetSecond returns the value of Second.
func (s *TestOK) GetSecond() OptStr {
	return s.Second
}

// GetThird returns the value of Third.
func (s *TestOK) GetThird() OptStr {
	return s.Third
}

// SetFirst sets the value of First.
func (s *TestOK) SetFirst(val OptStr) {
	s.First = val
}

// SetSecond sets the value of Second.
func (s *TestOK) SetSecond(val OptStr) {
	s.Second = val
}

// SetThird sets the value of Third.
func (s *TestOK) SetThird(val OptStr) {
	s.Third = val
}
