// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"io"
	"iter"
	"net/http"
	"sync"
	"sync/atomic"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/sse"
)

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/StreamChunk
type StreamChunk struct {
	Content string `json:"content"`
}

// GetContent returns the value of Content.
func (s *StreamChunk) GetContent() string {
	return s.Content
}

// SetContent sets the value of Content.
func (s *StreamChunk) SetContent(val string) {
	s.Content = val
}

// Ref: #/components/schemas/StreamDone
type StreamDone struct {
	Result OptString `json:"result"`
}

// GetResult returns the value of Result.
func (s *StreamDone) GetResult() OptString {
	return s.Result
}

// SetResult sets the value of Result.
func (s *StreamDone) SetResult(val OptString) {
	s.Result = val
}

// Ref: #/components/schemas/StreamError
type StreamError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *StreamError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *StreamError) SetMessage(val string) {
	s.Message = val
}

// StreamEventsOKClient reads events from the StreamEventsOK SSE stream.
type StreamEventsOKClient interface {
	sse.Client[StreamEventsOKEvent]
}

// StreamEventsOKSender sends events to the StreamEventsOK SSE stream.
type StreamEventsOKSender interface {
	sse.Sender[StreamEventsOKEvent]
}

// StreamEventsOK is a Server-Sent Events response stream.
type StreamEventsOK struct {
	// Events writes the stream events.
	//
	// It is called by the generated server after the response headers are
	// sent, until it returns. A nil Events sends an empty stream.
	//
	// Events is not used by the generated client.
	Events func(ctx context.Context, s StreamEventsOKSender) error
	// KeepAlive keeps an idle connection open while Events runs. It is called
	// concurrently with Events and shares the same sender, which is safe for
	// concurrent use. It should return when its context is canceled, which
	// happens once Events returns.
	//
	// If nil, a "keep-alive" comment is sent every [sse.DefaultKeepAliveInterval].
	// Set it to a function that returns immediately to disable keep-alive.
	//
	// KeepAlive is not used by the generated client.
	KeepAlive func(ctx context.Context, s StreamEventsOKSender) error
	resp      *http.Response
	decoder   *sse.Decoder
	connect   sseConnectFunc
	options   sseClientConfig
	stateMu   sync.RWMutex
	state     sse.State
	latestErr error
	closed    atomic.Bool
	closeCh   chan struct{}
	closeOnce sync.Once
}

func (s *StreamEventsOK) initSSEStream(
	connect sseConnectFunc,
	options sseClientConfig,
) {
	s.stateMu.Lock()
	defer s.stateMu.Unlock()
	if s.resp != nil {
		s.decoder = newSSEResponseDecoder(s.resp, options)
	}
	s.connect = connect
	s.options = options
	s.state = sse.StateOpen
	s.latestErr = nil
	s.closeCh = make(chan struct{})
}

// State returns the current stream state and the latest terminal or current reconnect error.
func (s *StreamEventsOK) State() (state sse.State, latestErr error) {
	s.stateMu.RLock()
	defer s.stateMu.RUnlock()
	return s.state, s.latestErr
}

func (s *StreamEventsOK) setState(state sse.State, latestErr error) {
	s.stateMu.Lock()
	s.state = state
	s.latestErr = latestErr
	s.stateMu.Unlock()
}

func (s *StreamEventsOK) withCloseContext(ctx context.Context,
) (context.Context, context.CancelFunc) {
	reconnectCtx, cancel := context.WithCancel(ctx)
	if s.closed.Load() {
		cancel()
		return reconnectCtx, func() {}
	}
	if s.closeCh == nil {
		return reconnectCtx, cancel
	}

	go func() {
		select {
		case <-s.closeCh:
			cancel()
		case <-reconnectCtx.Done():
		}
	}()
	return reconnectCtx, cancel
}

// Close closes the current stream and stops further reconnect attempts.
func (s *StreamEventsOK) Close() error {
	if !s.closed.CompareAndSwap(false, true) {
		return nil
	}
	s.stateMu.Lock()
	resp := s.resp
	s.resp = nil
	s.decoder = nil
	closeCh := s.closeCh
	s.state = sse.StateClosed
	s.latestErr = sse.ErrStreamClosed
	s.stateMu.Unlock()

	if closeCh != nil {
		s.closeOnce.Do(func() {
			close(closeCh)
		})
	}

	if resp == nil || resp.Body == nil {
		return nil
	}
	return resp.Body.Close()
}

// Next returns the next event from the stream, reconnecting when needed.
func (s *StreamEventsOK) Next(ctx context.Context,
) (StreamEventsOKEvent, error) {
	for {
		s.stateMu.RLock()
		resp, decoder, connect, options, latestErr := s.resp, s.decoder, s.connect, s.options, s.latestErr
		s.stateMu.RUnlock()
		if s.closed.Load() {
			var event StreamEventsOKEvent
			return event, sse.ErrStreamClosed
		}
		if decoder == nil {
			// No decoder means the stream is already terminal.
			if latestErr == nil {
				latestErr = sse.ErrStreamClosed
			}
			s.setState(sse.StateClosed, latestErr)
			var event StreamEventsOKEvent
			return event, latestErr
		}
		raw, err := decoder.Decode()
		if err == nil {
			s.setState(sse.StateOpen, nil)
			return s.decodeEvent(raw)
		}
		// Special case, on ErrEventTooLarge the current event is drained
		// without closing the stream.
		if errors.Is(err, sse.ErrEventTooLarge) {
			s.setState(sse.StateOpen, err)
			var event StreamEventsOKEvent
			return event, err
		}
		if !sse.IsReconnectableError(err) {
			s.setState(sse.StateClosed, err)
			var event StreamEventsOKEvent
			return event, err
		}
		if connect == nil {
			// Without a reconnect function, a reconnectable read error
			// becomes terminal.
			s.setState(sse.StateClosed, sse.ErrStreamClosed)
			var event StreamEventsOKEvent
			return event, sse.ErrStreamClosed
		}

		s.setState(sse.StateConnecting, err)
		reconnectCtx, cancel := s.withCloseContext(ctx)
		nextResp, nextDecoder, err := reconnectSSE(reconnectCtx, resp, decoder, connect, options, s)
		cancel()
		if s.closed.Load() {
			if nextResp != nil && nextResp.Body != nil {
				_ = nextResp.Body.Close()
			}
			var event StreamEventsOKEvent
			return event, sse.ErrStreamClosed
		}
		if err != nil {
			s.stateMu.Lock()
			s.resp = nil
			s.decoder = nil
			s.stateMu.Unlock()
			s.setState(sse.StateClosed, err)
			var event StreamEventsOKEvent
			return event, err
		}
		s.stateMu.Lock()
		s.resp = nextResp
		s.decoder = nextDecoder
		s.stateMu.Unlock()
		s.setState(sse.StateOpen, nil)
	}
}

// All iterates over stream events until the stream is closed, reconnecting when needed.
func (s *StreamEventsOK) All(ctx context.Context,
) iter.Seq2[StreamEventsOKEvent, error] {
	return func(yield func(StreamEventsOKEvent, error) bool) {
		for {
			event, err := s.Next(ctx)
			if err != nil {
				if !sse.IsReconnectableError(err) {
					return
				}
				var zero StreamEventsOKEvent
				if !yield(zero, err) {
					return
				}
				continue
			}
			if !yield(event, nil) {
				return
			}
		}
	}
}

func (s *StreamEventsOK) decodeEvent(raw sse.Event,
) (StreamEventsOKEvent, error) {
	e := jx.GetEncoder()
	e.ObjStart()
	e.FieldStart("id")
	e.Str(raw.ID)
	e.FieldStart("event")
	e.Str(raw.Type)
	e.FieldStart("data")
	switch raw.Type {
	case "chunk":
		e.Raw([]byte(raw.Data))
	case "done":
		e.Raw([]byte(raw.Data))
	case "error":
		e.Raw([]byte(raw.Data))
	case "log":
		if jx.Valid([]byte(raw.Data)) {
			e.Raw([]byte(raw.Data))
		} else {
			e.Str(raw.Data)
		}
	default:
		if jx.Valid([]byte(raw.Data)) {
			e.Raw([]byte(raw.Data))
		} else {
			e.Str(raw.Data)
		}
	}
	if raw.Retry != nil {
		e.FieldStart("retry")
		e.Int(int((*raw.Retry) / time.Millisecond))
	}
	e.ObjEnd()
	buf := e.Bytes()
	jx.PutEncoder(e)

	d := jx.DecodeBytes(buf)
	var event StreamEventsOKEvent
	if err := func() error {
		if err := event.Decode(d); err != nil {
			return err
		}
		if err := d.Skip(); err != io.EOF {
			return errors.New("unexpected trailing data")
		}
		return nil
	}(); err != nil {
		return event, err
	}
	return event, nil
}

// StreamEventsOKEvent represents sum type.
type StreamEventsOKEvent struct {
	// Type selects the active sum variant, switch on this field.
	Type                     StreamEventsOKEventType
	StreamEventsOKEventChunk StreamEventsOKEventChunk
	StreamEventsOKEventDone  StreamEventsOKEventDone
	StreamEventsOKEventError StreamEventsOKEventError
	StreamEventsOKEventLog   StreamEventsOKEventLog
}

// StreamEventsOKEventType is oneOf type of StreamEventsOKEvent.
type StreamEventsOKEventType string

// Possible values for StreamEventsOKEventType.
const (
	StreamEventsOKEventChunkStreamEventsOKEvent StreamEventsOKEventType = "chunk"
	StreamEventsOKEventDoneStreamEventsOKEvent  StreamEventsOKEventType = "done"
	StreamEventsOKEventErrorStreamEventsOKEvent StreamEventsOKEventType = "error"
	StreamEventsOKEventLogStreamEventsOKEvent   StreamEventsOKEventType = "log"
)

// IsStreamEventsOKEventChunk reports whether StreamEventsOKEvent is StreamEventsOKEventChunk.
func (s StreamEventsOKEvent) IsStreamEventsOKEventChunk() bool {
	return s.Type == StreamEventsOKEventChunkStreamEventsOKEvent
}

// IsStreamEventsOKEventDone reports whether StreamEventsOKEvent is StreamEventsOKEventDone.
func (s StreamEventsOKEvent) IsStreamEventsOKEventDone() bool {
	return s.Type == StreamEventsOKEventDoneStreamEventsOKEvent
}

// IsStreamEventsOKEventError reports whether StreamEventsOKEvent is StreamEventsOKEventError.
func (s StreamEventsOKEvent) IsStreamEventsOKEventError() bool {
	return s.Type == StreamEventsOKEventErrorStreamEventsOKEvent
}

// IsStreamEventsOKEventLog reports whether StreamEventsOKEvent is StreamEventsOKEventLog.
func (s StreamEventsOKEvent) IsStreamEventsOKEventLog() bool {
	return s.Type == StreamEventsOKEventLogStreamEventsOKEvent
}

// SetStreamEventsOKEventChunk sets StreamEventsOKEvent to StreamEventsOKEventChunk.
func (s *StreamEventsOKEvent) SetStreamEventsOKEventChunk(v StreamEventsOKEventChunk) {
	s.Type = StreamEventsOKEventChunkStreamEventsOKEvent
	s.StreamEventsOKEventChunk = v
}

// GetStreamEventsOKEventChunk returns StreamEventsOKEventChunk and true boolean if StreamEventsOKEvent is StreamEventsOKEventChunk.
func (s StreamEventsOKEvent) GetStreamEventsOKEventChunk() (v StreamEventsOKEventChunk, ok bool) {
	if !s.IsStreamEventsOKEventChunk() {
		return v, false
	}
	return s.StreamEventsOKEventChunk, true
}

// NewStreamEventsOKEventChunkStreamEventsOKEvent returns new StreamEventsOKEvent from StreamEventsOKEventChunk.
func NewStreamEventsOKEventChunkStreamEventsOKEvent(v StreamEventsOKEventChunk) StreamEventsOKEvent {
	var s StreamEventsOKEvent
	s.SetStreamEventsOKEventChunk(v)
	return s
}

// SetStreamEventsOKEventDone sets StreamEventsOKEvent to StreamEventsOKEventDone.
func (s *StreamEventsOKEvent) SetStreamEventsOKEventDone(v StreamEventsOKEventDone) {
	s.Type = StreamEventsOKEventDoneStreamEventsOKEvent
	s.StreamEventsOKEventDone = v
}

// GetStreamEventsOKEventDone returns StreamEventsOKEventDone and true boolean if StreamEventsOKEvent is StreamEventsOKEventDone.
func (s StreamEventsOKEvent) GetStreamEventsOKEventDone() (v StreamEventsOKEventDone, ok bool) {
	if !s.IsStreamEventsOKEventDone() {
		return v, false
	}
	return s.StreamEventsOKEventDone, true
}

// NewStreamEventsOKEventDoneStreamEventsOKEvent returns new StreamEventsOKEvent from StreamEventsOKEventDone.
func NewStreamEventsOKEventDoneStreamEventsOKEvent(v StreamEventsOKEventDone) StreamEventsOKEvent {
	var s StreamEventsOKEvent
	s.SetStreamEventsOKEventDone(v)
	return s
}

// SetStreamEventsOKEventError sets StreamEventsOKEvent to StreamEventsOKEventError.
func (s *StreamEventsOKEvent) SetStreamEventsOKEventError(v StreamEventsOKEventError) {
	s.Type = StreamEventsOKEventErrorStreamEventsOKEvent
	s.StreamEventsOKEventError = v
}

// GetStreamEventsOKEventError returns StreamEventsOKEventError and true boolean if StreamEventsOKEvent is StreamEventsOKEventError.
func (s StreamEventsOKEvent) GetStreamEventsOKEventError() (v StreamEventsOKEventError, ok bool) {
	if !s.IsStreamEventsOKEventError() {
		return v, false
	}
	return s.StreamEventsOKEventError, true
}

// NewStreamEventsOKEventErrorStreamEventsOKEvent returns new StreamEventsOKEvent from StreamEventsOKEventError.
func NewStreamEventsOKEventErrorStreamEventsOKEvent(v StreamEventsOKEventError) StreamEventsOKEvent {
	var s StreamEventsOKEvent
	s.SetStreamEventsOKEventError(v)
	return s
}

// SetStreamEventsOKEventLog sets StreamEventsOKEvent to StreamEventsOKEventLog.
func (s *StreamEventsOKEvent) SetStreamEventsOKEventLog(v StreamEventsOKEventLog) {
	s.Type = StreamEventsOKEventLogStreamEventsOKEvent
	s.StreamEventsOKEventLog = v
}

// GetStreamEventsOKEventLog returns StreamEventsOKEventLog and true boolean if StreamEventsOKEvent is StreamEventsOKEventLog.
func (s StreamEventsOKEvent) GetStreamEventsOKEventLog() (v StreamEventsOKEventLog, ok bool) {
	if !s.IsStreamEventsOKEventLog() {
		return v, false
	}
	return s.StreamEventsOKEventLog, true
}

// NewStreamEventsOKEventLogStreamEventsOKEvent returns new StreamEventsOKEvent from StreamEventsOKEventLog.
func NewStreamEventsOKEventLogStreamEventsOKEvent(v StreamEventsOKEventLog) StreamEventsOKEvent {
	var s StreamEventsOKEvent
	s.SetStreamEventsOKEventLog(v)
	return s
}

type StreamEventsOKEventChunk struct {
	Event string      `json:"event"`
	Data  StreamChunk `json:"data"`
	ID    string      `json:"id"`
	Retry OptInt      `json:"retry"`
}

// GetEvent returns the value of Event.
func (s *StreamEventsOKEventChunk) GetEvent() string {
	return s.Event
}

// GetData returns the value of Data.
func (s *StreamEventsOKEventChunk) GetData() StreamChunk {
	return s.Data
}

// GetID returns the value of ID.
func (s *StreamEventsOKEventChunk) GetID() string {
	return s.ID
}

// GetRetry returns the value of Retry.
func (s *StreamEventsOKEventChunk) GetRetry() OptInt {
	return s.Retry
}

// SetEvent sets the value of Event.
func (s *StreamEventsOKEventChunk) SetEvent(val string) {
	s.Event = val
}

// SetData sets the value of Data.
func (s *StreamEventsOKEventChunk) SetData(val StreamChunk) {
	s.Data = val
}

// SetID sets the value of ID.
func (s *StreamEventsOKEventChunk) SetID(val string) {
	s.ID = val
}

// SetRetry sets the value of Retry.
func (s *StreamEventsOKEventChunk) SetRetry(val OptInt) {
	s.Retry = val
}

type StreamEventsOKEventDone struct {
	Event string     `json:"event"`
	Data  StreamDone `json:"data"`
	ID    string     `json:"id"`
	Retry OptInt     `json:"retry"`
}

// GetEvent returns the value of Event.
func (s *StreamEventsOKEventDone) GetEvent() string {
	return s.Event
}

// GetData returns the value of Data.
func (s *StreamEventsOKEventDone) GetData() StreamDone {
	return s.Data
}

// GetID returns the value of ID.
func (s *StreamEventsOKEventDone) GetID() string {
	return s.ID
}

// GetRetry returns the value of Retry.
func (s *StreamEventsOKEventDone) GetRetry() OptInt {
	return s.Retry
}

// SetEvent sets the value of Event.
func (s *StreamEventsOKEventDone) SetEvent(val string) {
	s.Event = val
}

// SetData sets the value of Data.
func (s *StreamEventsOKEventDone) SetData(val StreamDone) {
	s.Data = val
}

// SetID sets the value of ID.
func (s *StreamEventsOKEventDone) SetID(val string) {
	s.ID = val
}

// SetRetry sets the value of Retry.
func (s *StreamEventsOKEventDone) SetRetry(val OptInt) {
	s.Retry = val
}

type StreamEventsOKEventError struct {
	Event string      `json:"event"`
	Data  StreamError `json:"data"`
	ID    string      `json:"id"`
	Retry OptInt      `json:"retry"`
}

// GetEvent returns the value of Event.
func (s *StreamEventsOKEventError) GetEvent() string {
	return s.Event
}

// GetData returns the value of Data.
func (s *StreamEventsOKEventError) GetData() StreamError {
	return s.Data
}

// GetID returns the value of ID.
func (s *StreamEventsOKEventError) GetID() string {
	return s.ID
}

// GetRetry returns the value of Retry.
func (s *StreamEventsOKEventError) GetRetry() OptInt {
	return s.Retry
}

// SetEvent sets the value of Event.
func (s *StreamEventsOKEventError) SetEvent(val string) {
	s.Event = val
}

// SetData sets the value of Data.
func (s *StreamEventsOKEventError) SetData(val StreamError) {
	s.Data = val
}

// SetID sets the value of ID.
func (s *StreamEventsOKEventError) SetID(val string) {
	s.ID = val
}

// SetRetry sets the value of Retry.
func (s *StreamEventsOKEventError) SetRetry(val OptInt) {
	s.Retry = val
}

type StreamEventsOKEventLog struct {
	Event string `json:"event"`
	Data  string `json:"data"`
	ID    string `json:"id"`
	Retry OptInt `json:"retry"`
}

// GetEvent returns the value of Event.
func (s *StreamEventsOKEventLog) GetEvent() string {
	return s.Event
}

// GetData returns the value of Data.
func (s *StreamEventsOKEventLog) GetData() string {
	return s.Data
}

// GetID returns the value of ID.
func (s *StreamEventsOKEventLog) GetID() string {
	return s.ID
}

// GetRetry returns the value of Retry.
func (s *StreamEventsOKEventLog) GetRetry() OptInt {
	return s.Retry
}

// SetEvent sets the value of Event.
func (s *StreamEventsOKEventLog) SetEvent(val string) {
	s.Event = val
}

// SetData sets the value of Data.
func (s *StreamEventsOKEventLog) SetData(val string) {
	s.Data = val
}

// SetID sets the value of ID.
func (s *StreamEventsOKEventLog) SetID(val string) {
	s.ID = val
}

// SetRetry sets the value of Retry.
func (s *StreamEventsOKEventLog) SetRetry(val OptInt) {
	s.Retry = val
}
