// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/sse"
	"go.opentelemetry.io/otel/trace"
)

// encodeStreamEventsOKEvent encodes StreamEventsOKEvent as a Server-Sent Event.
func encodeStreamEventsOKEvent(event StreamEventsOKEvent) (sse.Event, error) {
	var raw sse.Event
	e := jx.GetEncoder()
	defer jx.PutEncoder(e)
	event.Encode(e)

	// Event schema describes the full event envelope, so the standard fields
	// are taken from the encoded object.
	if err := jx.DecodeBytes(e.Bytes()).ObjBytes(func(d *jx.Decoder, key []byte) error {
		if d.Next() == jx.Null {
			return d.Skip()
		}
		switch string(key) {
		case "id":
			v, err := d.Str()
			if err != nil {
				return err
			}
			raw.ID = v
		case "event":
			v, err := d.Str()
			if err != nil {
				return err
			}
			raw.Type = v
		case "retry":
			v, err := d.Int64()
			if err != nil {
				return err
			}
			retry := time.Duration(v) * time.Millisecond
			raw.Retry = &retry
		case "data":
			v, err := d.Raw()
			if err != nil {
				return err
			}
			// String data is sent as-is, any other value is sent as JSON.
			if v.Type() == jx.String {
				data, err := jx.DecodeBytes(v).Str()
				if err != nil {
					return err
				}
				raw.Data = data
				return nil
			}
			raw.Data = string(v)
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return raw, errors.Wrap(err, "encode event")
	}
	return raw, nil
}

func encodeStreamEventsResponse(ctx context.Context, response *StreamEventsOK, w http.ResponseWriter, span trace.Span) error {
	w.Header().Set("Content-Type", "text/event-stream")
	// Event stream must not be cached, otherwise events may be delayed.
	w.Header().Set("Cache-Control", "no-cache")
	w.WriteHeader(200)

	enc := sse.NewEncoder(w)
	// Flush the headers, so that the client does not wait for the first event.
	if err := enc.Flush(); err != nil {
		return errors.Wrap(err, "flush")
	}
	if response.Events != nil {
		sender := sse.NewSender(enc, encodeStreamEventsOKEvent)

		// Keep-alive runs concurrently with Events and is stopped once
		// Events returns by canceling streamCtx.
		streamCtx, cancel := context.WithCancel(ctx)
		defer cancel()

		keepAlive := response.KeepAlive
		if keepAlive == nil {
			keepAlive = func(ctx context.Context, s StreamEventsOKSender) error {
				return sse.KeepAlive(ctx, s)
			}
		}
		keepAliveDone := make(chan struct{})
		go func() {
			defer close(keepAliveDone)
			_ = keepAlive(streamCtx, sender)
		}()

		sErr := response.Events(streamCtx, sender)
		cancel()
		<-keepAliveDone
		if sErr != nil {
			// Response is already sent, so the error can't be reported to the client.
			return errors.Join(errors.Wrap(sErr, "write events"), ht.ErrResponseSent)
		}
	}

	return nil
}
