// Code generated by ogen, DO NOT EDIT.

package api

import (
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func decodeStreamEventsResponse(resp *http.Response) (res *StreamEventsOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "text/event-stream":
			response := StreamEventsOK{resp: resp}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
