// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// StreamEvents implements streamEvents operation.
//
// POST /stream
func (UnimplementedHandler) StreamEvents(ctx context.Context) (r *StreamEventsOK, _ error) {
	return r, ht.ErrNotImplemented
}
